### ISSUE TITLE
关于checkpoint

### ISSUE THREAD

**Issue by martellolee** [heroinlin/detectron2_visualization#1]
您好，请问代码中用到的模型文件osnet_x0_5_62_1.6187.pth是额外训练出来的吗？用到了哪些数据集？是否方便提供代码中的模型文件osnet_x0_5_62_1.6187.pth？

**Comment by heroinlin** [comment]
> 您好，请问代码中用到的模型文件osnet_x0_5_62_1.6187.pth是额外训练出来的吗？用到了哪些数据集？是否方便提供代码中的模型文件osnet_x0_5_62_1.6187.pth？

模型是另外训练的，这个很早以前写的，我这边也找不到这个模型文件了。 你想试的话可以换一个模型，地址在下边
链接:https://pan.baidu.com/s/1NkqgK8MnE3TDp2vDam8v3w 密码:6e0c
这个模型的话把 configs/osnet.yaml中的CLASS_NUM改成5360
模型是做行人重识别的，数据集用的以前公司的数据集，你可以理解类似market1501数据集。

**Comment by martellolee** [comment]
谢谢！
